# Generated by Django 2.0 on 2017-12-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0002_auto_20171220_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='password',
            new_name='password_hash',
        ),
    ]
