# Generated by Django 2.0 on 2017-12-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0003_auto_20171220_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='password_hash',
            new_name='password',
        ),
    ]
