# Generated by Django 2.0 on 2017-12-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0004_auto_20171220_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FilePathField(max_length=256),
        ),
    ]
