# Generated by Django 2.0 on 2017-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0005_auto_20171224_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_feched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
