# Generated by Django 2.0 on 2017-12-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0006_auto_20171224_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
