# Generated by Django 2.0 on 2017-12-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0008_auto_20171224_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='labelled_images',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='total_images',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
