# Generated by Django 2.0 on 2017-12-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0009_auto_20171227_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_fetched',
        ),
        migrations.AddField(
            model_name='item',
            name='votes_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
