# Generated by Django 2.0 on 2017-12-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0010_auto_20171228_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(default='Una descrizione molto interessante', max_length=256),
            preserve_default=False,
        ),
    ]
