# Generated by Django 2.0 on 2018-01-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitalian', '0012_remove_collection_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='link',
        ),
    ]
